name: flucompy
description: A compass made with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+9

environment:
  sdk: '>=2.18.0-109.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  hack2s_flutter_util:
    path: ../../hack2s_flutter_util/hack2s_flutter_util

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/compass_direction_1.png
    - assets/compass_direction_2.png
    - assets/compass_direction_3.png
    - assets/compass_direction_4.png
    - assets/compass_direction_5.png
    - assets/compass_direction_6.png
    - assets/compass_direction_7.png
    - assets/compass_direction_8.png
    - assets/compass_direction_9.png
    - assets/compass_direction_10.png